### ISSUE TITLE
Index error during 'make train_lstm'

### ISSUE THREAD

**Issue by RainyTong** [cecilialeiqi/adversarial_text#2]
I got this error when executing the command `make` in **step 1**. Can anyone help to solve it?
Thanks!
```
Traceback (most recent call last):
  File "train_LSTM.py", line 102, in <module>
    main()
  File "train_LSTM.py", line 91, in main
    running_loss += loss.data[0]
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number
100%|█████████▉| 399768/400000 [03:09<00:00, 2111.93it/s] 
make: *** [train_lstm] Error 1
```

**Comment by RainyTong** [comment]
Solved. Caused by different torch version. 
Change `running_loss += loss.data[0]` to `running_loss += loss.data`.
