### ISSUE TITLE
ValueError encountered with KeyedVectors within discrete_attack.py 

### ISSUE THREAD

**Issue by VPasca** [cecilialeiqi/adversarial_text#3]
Hello, I am trying to run your adversarial attack for spam generation on the trained CNN and LSTM models from your repository. However, on Step 4 (generate adversarial examples) I am getting a ValueError error when I type make attack_cnn. I have downloaded the paragram embeddings and included the path to them in the makefile as described in Step 2. But, when I try to run make attack_cnn, it fails to get past the line "self.w2v = KeyedVectors.load_word2vec_format(opt.embedding_path, binary=False)". I get the error saying ValueError: invalid literal for int() with base 10: ','. I know from the readme.txt for the paragram embeddings that each line in the file has the token at the start of the line followed by its embedding numbers. So I know that the first line of the embeddings has the comma token (,) then its embeddings. Thus, it seems like KeyedVectors is not expecting the token at the start of the line, but rather numbers. 

Here is the full error message I get.

`make attack_cnn
python3 discrete_attack.py 2 CNN ../data/train.tsv ../data/test.tsv ../data/changed_cnn_train --embedding_path ../paragram_300_sl999/paragram_300_sl999/paragram_300_sl999.txt   --model_path ../model/model_cnn.pt 20000 --first_label FAKE

Initializing language model...
Initializing word vectors...
Traceback (most recent call last):
  File "discrete_attack.py", line 388, in <module>
    main()
  File "discrete_attack.py", line 365, in main
    attacker=Attacker(X_train,opt)
  File "discrete_attack.py", line 111, in __init__
    self.w2v = KeyedVectors.load_word2vec_format(opt.embedding_path, binary=False)
  File "/home/vlad-ubuntu/anaconda3/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 1498, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/home/vlad-ubuntu/anaconda3/lib/python3.7/site-packages/gensim/models/utils_any2vec.py", line 344, in _load_word2vec_format
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
  File "/home/vlad-ubuntu/anaconda3/lib/python3.7/site-packages/gensim/models/utils_any2vec.py", line 344, in <genexpr>
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
ValueError: invalid literal for int() with base 10: ','
Makefile:14: recipe for target 'attack_cnn' failed
make: *** [attack_cnn] Error 1
`

If you could please help me with this issue, it would be very much appreciated.

Thank you.

**Comment by VPasca** [comment]
The problem was with the pargram txt embeddings files. To get it to work, you need to insert 1703756 300 at the top of the file. This represents the vocabulary size and number of embeddings (numbers) per token.
